# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    paths:
      - 'test.csv'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.11  # Replace with the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your dependencies installation command

      - name: Run Python script
        run: |
          echo "$PWD"
          python script.py >> log.txt  # Replace with the path to your Python script
          echo "$LS"
        
      - name: Save Log File
        run: |
          # Get the latest commit SHA
          COMMIT_SHA=$(git rev-parse HEAD)

          # Read the log file content
          LOG_CONTENT=$(cat log.txt)

          # Create the log file in the repository
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"message\": \"Add log file\", \"content\": \"$LOG_CONTENT\"}" \
            "https://api.github.com/repos/{owner}/{repo}/contents/log.txt?ref=$COMMIT_SHA"
